travis:
  secure:
    BINSTAR_TOKEN: VV6/L1tJt1B29slQJUBNOVj0Up9UzhLSa8QR9mYvBBwfWayxnt7UZIsrTsioFwES8FXLIsj0CdPTNgsSmyzuhAQUSOXwNc+4+OmaG6o9Y4F4piBCj5A8+dnRW7kL8NK1hn/nXS2amTwbgG1SuzAHtALEYAfGEpUY/EqZAxrmL+HjZbduw9Es2xZVapuCHia9GA34IHPjzvV+Al+JeYRt5vAPsFsYRoNDjtp1EwjDEE+lILvXMzBPm+WlZttDLLQ7SSdhunAXcv+AQyM21b4g8/ZE9VXvUxZukHmn15hCLbq8+SB7QPgyzaiaBgZLn91DEwDDG/SdO6FcP1CocVc9Yy92erFPIUvN07f4VK0INIsEUT6ZPYogWSUBZPm00mrYhyocfXF32r2o04PhE2mXrDnqyN8+tYLsAWLGNvG2IXAM3Ga2kgjrppSpDAp7fvuHcNMdRMAnRiUusgbNRG8JrlcmJL1hqwZhhsS5lpGXTj0eiIRGD34LCJT4pcMu3h2lS7FuzceGdyyg/e+BC6xN22d4pUajVh/G7FBrNDnHVuI0SV4aUCohmCUy8eM0W6fDNOEPzJisDIn1WTXB6n5+YodfJQQ2dBNuWkAlI33JCEl1kIau3gbNdeJRY+duBdsbaPkN/TruNvYkm7XVOs2H2LOTYR8RgVJW2yLVC1nf2Ls=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
