travis:
  secure:
    BINSTAR_TOKEN: OCWB8r+IaKK/SQ2WtXfxJ9ErCuJ/iv59x6uvN3aVin3V3JgnuDTYOTPTm5UrF/rBWrDHva4Gva/EKkmXmDqjRozacyUADbr7EIAeU+vWRRavrrmt8J/DapN80QLMtAX75c8STbSPsp1sX9bDGXQUfGz5aww9dAAYmIlsX3Cy7vRYd33VNPqJ2In+81rEqdtI0OXFALp6OZOacXzIu/PjBmIvaZqKXo3ih09B+CBUNPUM1qDKEI+529afZDSxEdmdIrgXgXWA7WKU5NCnlM7T7zhVZWtPnaDJYpMmRixojLi7ayoDdaJqpwHV8raGTxXHD4DnjzkiSkOdLOGmKr8l596gY6QLdKilWKdflz9m+PpT5XMxr6zd40+2S9OZWEIqAcHDEIuFDA6gCVSHy4wlm4Y8R5CZ0mvGItIJ5C6JUot0ntg+f8JmtkgxYabYDqOx9LbUH/0Wefmk2OR8dQbysCiZrLoggmgZNPW3zYYUyjml+kTfI/nBrJR1orXeBwjjO3sk+cziaSGNWSu/Y5695uNrvVSd7mzhlJkIMNcLkov3GYwBKVLiFUCfGKy2avInPg9ATHpmNOVhHa866QGpU6nTaxv+a1DjXXC8kwc7RQi53AyWGOKhAuDIR+fZi5r1O9CQo6Syzs9P62uum6jVq8SeKaJb49QRQ2XARtst7/E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
