travis:
  secure:
    BINSTAR_TOKEN: fyRgCluANZw5lBhsGeSNVnhhFjV0q2xOpFbElrQ2Ek2w64j4eDkCiMgAL9CFEcb7YWlj3mJ3R5ws45szVSmA4/qRhkK9EOAYfay4PhPPOVtuDOOo6QxUQNm7hFVzWvOOMAxpD441gak88WbjX68v34zlSUpdBtFsVTegsJaniZ3KtnXK5XWrjPGL2zPyd4/YDLbbKCsoncELTqZBZEKA/LmP7q0C3B8zwrJdVuk6aoCjUJmu6x1UKJP5wcdyPYY1x3Dxj+6f/3rNmydgH6uPItrwGGYKG7/vL7N1pH/TQ3AlFpHra347lp6aykKGW96250Qw8Ydf/cFmabHeMhmXftAgRcgUg69t+yjUU3amIRS6/7Z1dXOSAVtAQb5wk17mAr8DrQggezxkLjqb3/dclpNCFvkvRmpQxn3g8FHicBnZj82ZDrPVhtRK3ICZg3tHaQWJ6tPvs2HR1LXvOvTL7uvDmuaj0m/qd6I5pHheZjKlDnFhJvTWjxbQmKlgsOzFqAyqV72piZ57pWVmlwjukGgPOufQpOz0cxnXBbobBZF3GsZejx8mPVuXRE0WKzNBKytK2ccNmd7ICuLLBBcWbwH0xECY6KAm1eUDuXUueBbfbr5Gyw0AhzR7EHEYJd7Hz0A2B0NXDl0q2JSBmmWdo6NJAdDIky0fDOg0dDWtdqE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
